### ISSUE TITLE
Cambios en algunas reglas de negocio

### ISSUE THREAD

**Issue by k31kur0n0** [belluccifranco/sic-api#204]
- Renglones de pedido pregunta por isEmpty y tira NPE, en validaciones
- Verificar que el estado del pedido a modificar o alta se encuentren en la enum
- Refactoring en GUI_CerrarVenta para eliminar el model ResultadosFactura
- Set clientes predeterminado debe recibir solo un id, actualmente recibe el object completo
- Cortar el json para que no devuelva el pass y permisosAdmin de Usuario
- Refactorizar todos los repository para que el guardar queden como Factura, para devolver el estado actual de la entity persistida
- En los delete, lanzar un msj si no se eucuentra la entity por ese id. Usar la nueva exception EntityNotFoundException

- Se pueden dar de alta muchas cajas sin ninguna restricción del día, debería permitir solo una caja por día.
- Se pueden dar de alta más de una forma de pago predeterminada, lo cual no debería permitirse, esto se repite en clientes.
- El código en producto y proveedor debe ir vació, pero debe estar porque si no arroja un npe, lo mismo proveedor.
- Los códigos se pueden repetir.
- En las criterias que se busca por país, provincia y localidad, no se considera la posibilidad de un id distinto de null, que no exista realmente. npe

**Comment by belluccifranco** [comment]
@k31kur0n0 actualizada la descripcion del ticket
